### ISSUE TITLE
Mostrar os últimos commits

### ISSUE THREAD

**Issue by fabriciorissetto** [bernardobrezende/gh-x9#6]
Hoje está mostrando só o último.

Seria interessante adicionar uma listagem com os últimos 5 commits, ou os commits dos últimos 2 dias...

![image](https://cloud.githubusercontent.com/assets/1520059/10794919/60b83d12-7d7e-11e5-9fd9-d364bc52abe8.png)

**Comment by bernardobrezende** [comment]
https://github.com/bernardobrezende/gh-x9/pull/13
